// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package licensepoolmanager.actions;

import java.util.Collection;
import java.util.Date;
import licensepoolmanager.proxies.Account;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Retrieves the currently active users and sets their LastOnline attribute, which is used to constrain the active sessions windows.
 */
public class CheckOnlineUsers extends CustomJavaAction<Boolean>
{
	public CheckOnlineUsers(IContext context)
	{
		super(context);
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		//Retrieve active sessions
		Collection<? extends ISession> activeSessions = Core
		.getActiveSessions();
		
		//Get current date time
		Date date = new Date();
				
		//Initialize account objects for the active sessions if these are Account objects. 		
		for (ISession i : activeSessions) {

			IMendixObject user = i.getUser().getMendixObject();
			
			if (Core.isSubClassOf(Account.getType(), user.getType())) {

				Account account = Account.initialize(
						this.getContext(), user);
				
				//Set LastOnline and Commit
				account.setLastOnline(date);
				account.commit();
				
				}
			}
				
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "CheckOnlineUsers";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
